[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fair_launch_solana_program = "9skK6yTzZgPmkYwwdwsVw9GzFkjHd9pVUnKJWsGYpv7m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.testnet.v1.sonic.game"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
